import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AccountContextProvider } from '@/context/account-context';
import { MainStateMachineContextProvider } from '@/context/state-machine-context';
import DefaultLayout from '@/layouts/default';
import { GenericEventProvider } from '@/providers/GerericEventProvider';
import { Web3Provider } from '@/providers/Web3Provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Sophon Account - Auth Server',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccountContextProvider>
          <MainStateMachineContextProvider>
            <Web3Provider>
              <GenericEventProvider />
              <DefaultLayout>{children}</DefaultLayout>
            </Web3Provider>
          </MainStateMachineContextProvider>
        </AccountContextProvider>
      </body>
    </html>
  );
}
