import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/providers/Web3Provider";
import DefaultLayout from "@/layouts/default";
import { AccountContextProvider } from "@/context/account-context";
import { GenericEventProvider } from "@/providers/GerericEventProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sophon Account - Auth Server",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccountContextProvider>
          <Web3Provider>
            <GenericEventProvider />
            <DefaultLayout>{children}</DefaultLayout>
          </Web3Provider>
        </AccountContextProvider>
      </body>
    </html>
  );
}
