export const verifiedAbi = [
  {
    inputs: [],
    name: "aBool",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "anAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNumber",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getString",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTestStruct",
    outputs: [
      {
        components: [
          { internalType: "string", name: "testString", type: "string" },
          { internalType: "uint256", name: "testNumber", type: "uint256" },
          { internalType: "address", name: "testAddress", type: "address" },
          { internalType: "bool", name: "testBool", type: "bool" },
        ],
        internalType: "struct TestContract.TestStruct",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_anAddress", type: "address" }],
    name: "setAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bool", name: "_aBool", type: "bool" }],
    name: "setBool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_aNumber", type: "uint256" }],
    name: "setNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_aString", type: "string" }],
    name: "setString",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "test", type: "string" },
      {
        components: [
          { internalType: "string", name: "testString", type: "string" },
          { internalType: "uint256", name: "testNumber", type: "uint256" },
          { internalType: "address", name: "testAddress", type: "address" },
          { internalType: "bool", name: "testBool", type: "bool" },
        ],
        internalType: "struct TestContract.TestStruct",
        name: "_testStruct",
        type: "tuple",
      },
    ],
    name: "setStruct",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
